#
# Default oh-my-zsh configuration (updated NH 20220620)
#

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"
HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time
zstyle ':omz:update' mode auto      # update automatically without asking

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13
zstyle ':omz:update' frequency 30

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  colorize
  git
  macos
)
#  emacs
#  postgres
#  rails
#  ruby
#  emoji

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi
export EDITOR='nano'

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"



#
# Custom configuration starts here... (NH 20220620)
#

# Disable ~/.oh-my-zsh/lib/history.zsh
unsetopt share_history

# Disable other history procedures
# unsetopt hist_append
# unsetopt hist_expand
# HISTFILE=
#HISTSIZE=SAVEHIST=0

# Don't create ~/.zsh_history file
HISTFILE=/dev/null

# Enable HIST_IGNORE_SPACE (commands that follow a space will not be saved in history, e.g. ' echo "Foo"')
setopt histignorespace


# Initialize rbenv
eval "$(rbenv init - zsh)"

# Initialize nvs
export NVS_HOME="$HOME/.nvs"
[ -s "$NVS_HOME/nvs.sh" ] && . "$NVS_HOME/nvs.sh"



#
# .bashrc
# (since macOS is now including zsh instead of bash by default I'm merging all the former bash-related files into here; NH 20220620)
#

# Set path
#export PATH="/usr/local/bin:$PATH"
#export PATH="/usr/local/sbin:$PATH"
#export PATH="/usr/local/opt/ruby/bin:$PATH"


# MariaDB
export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/openssl/lib/


# Python
export PATH="/opt/homebrew/opt/python@3.10/libexec/bin:$PATH"


# PostgreSQL 15
export PATH="/opt/homebrew/opt/postgresql@15/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/postgresql@15/lib"
export CPPFLAGS="-I/opt/homebrew/opt/postgresql@15/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/postgresql@15/lib/pkgconfig"


# Ruby compiler config
#export LDFLAGS="-L/usr/local/opt/ruby/lib"
#export CPPFLAGS="-I/usr/local/opt/ruby/include"
#export PKG_CONFIG_PATH="/usr/local/opt/ruby/lib/pkgconfig"


# SQLite 3
export PATH="/opt/homebrew/opt/sqlite/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/sqlite/lib"
export CPPFLAGS="-I/opt/homebrew/opt/sqlite/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/sqlite/lib/pkgconfig"



# Disable homebrew analytics (Ugh, yuck!)
export HOMEBREW_NO_ANALYTICS=1


# Set default language
export LC_ALL="en_US.UTF-8"
export LANG="en_US"
export LANGUAGE="en_US:en"


# Set default editor
#export EDITOR="nano -w"
export EDITOR="/usr/local/bin/mate -w"



#
# .bash_profile
# (since macOS is now including zsh instead of bash by default I'm merging all the former bash-related files into here; NH 20220620)
#


# Aliases

# General
alias reload='source ~/Development/dotfiles/zsh/zshrc'

# Capistrano
alias deploy='bundle exec cap production deploy'

# Finder
alias d='~/Desktop'
alias dev='~/Development'

# Git
alias commits='git log --date=format:"%Y-%m-%d %H:%M" --pretty=format:"%C(auto,green)[%h]%C(auto,reset) %C(auto,blue)%an%C(auto,reset) %C(auto,yellow)%ad%C(auto,reset): %s" -50'
alias ga='git add -A'
alias gp='git push origin head'
alias gs='git status'
alias gpl='git pull'
alias gc='git commit -m'

# Puma
alias puma-log='nano ~/Library/Logs/puma-dev.log'
alias puma-purge-log='echo "" > ~/Library/Logs/puma-dev.log'
alias puma-restart='pkill -USR1 puma-dev'
alias puma-stop-alt='launchctl unload /Users/nilshaebel/Library/LaunchAgents/io.puma.dev.plist'
alias puma-start-alt='launchctl load /Users/nilshaebel/Library/LaunchAgents/io.puma.dev.plist'

# Rails
alias backup_db='bundle exec cap production server:backup_database'
alias credit='bundle exec rails credentials:edit'
alias el='echo "" > log/development.log'
alias rc='bundle exec rails console'
alias rs='bundle exec rails s'

# youtube-dl
alias audio='youtube-dl -x -f bestaudio --audio-format mp3'
alias video='youtube-dl -f bestvideo+bestaudio'


# set default directory
cd ~/Development

# load private configuration
source ~/Development/dotfiles-private/zshrc_private
