#
# .bash_profile
#


#
# Include .bashrc
#

source ~/.bashrc



#
# Aliases
#

# General
alias reload='source ~/Development/dotfiles/bash/bash_profile'

# Capistrano
alias deploy='bundle exec cap production deploy'

# Finder
alias d='~/Desktop'
alias dev='~/Development'

# Git
alias ga='git add -A'
alias gp='git push origin head'
alias gs='git status'
alias gpl='git pull'
alias gplh='git pull origin head'
alias gc='git commit -m'

# PostgreSQL
#alias pg-start='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
alias pg-start='/usr/local/opt/postgresql/bin/postgres -D /usr/local/var/postgres'
alias pg-stop='pg_ctl -D /usr/local/var/postgres stop -s -m fast'

# Puma
alias puma-log='nano ~/Library/Logs/puma-dev.log'
alias puma-purge-log='echo "" > ~/Library/Logs/puma-dev.log'
alias puma-restart='pkill -USR1 puma-dev'
alias puma-stop-alt='launchctl unload /Users/nilshaebel/Library/LaunchAgents/io.puma.dev.plist'
alias puma-start-alt='launchctl load /Users/nilshaebel/Library/LaunchAgents/io.puma.dev.plist'

# Rails
alias credit='bundle exec rails credentials:edit'
alias dbdump='bundle exec cap production server:backup_database'
alias el='echo "" > log/development.log'
alias rc='bundle exec rails console'
alias rs='bundle exec rails s'

# youtube-dl
alias audio='youtube-dl -x -f bestaudio --audio-format mp3'
alias video='youtube-dl -f bestvideo+bestaudio'

#
# set default directory
#

cd ~/Development



#
# load private configuration
#

source ~/Development/dotfiles-private/bash_profile_private
