#
# .bash_profile
#


#
# Include .bashrc
#

source ~/.bashrc



#
# Aliases
#

# General
alias dev='~/Development'
alias reload='source ~/Development/dotfiles/bash/bash_profile'

# Capistrano
alias deploy='cap production deploy'

# Git
alias ga='git add -A'
alias gp='git push origin head'
alias gs='git status'
alias gpl='git pull'
alias gplh='git pull origin head'
alias gc='git commit -m'

# PostgreSQL
alias pg-start='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
alias pg-stop='pg_ctl -D /usr/local/var/postgres stop -s -m fast'

# Puma
alias puma-log='nano ~/Library/Logs/puma-dev.log'
alias puma-purge-log='echo "" > ~/Library/Logs/puma-dev.log'
alias puma-restart='pkill -USR1 puma-dev'
alias puma-stop-alt='launchctl unload /Users/nilshaebel/Library/LaunchAgents/io.puma.dev.plist'
alias puma-start-alt='launchctl load /Users/nilshaebel/Library/LaunchAgents/io.puma.dev.plist'

# Rails
alias el='echo "" > log/development.log'
alias credit='bundle exec rails credentials:edit'


#
# set default directory
#

cd ~/Development



#
# load private configuration
#

source ~/Development/dotfiles-private/bash_profile_private
